projects:
  yearlongprojectteam20app:
    schemaPath: amplify/backend/api/yearlongprojectteam20app/build/schema.graphql
    includes:
      - src/graphql/*/**/
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ca-central-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
